[package]
name = "versions-replacer"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
argh = { workspace = true }
cargo_metadata = { workspace = true }
color-eyre = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true, features = ["unicode-perl"] }
serde = { workspace = true, features = ["derive"] }
walkdir = { workspace = true }
