[package]
name = "fuels"
version = "0.10.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK."

[dependencies]
fuels-abigen-macro = { version = "0.10.0", path = "../fuels-abigen-macro" }
fuels-contract = { version = "0.10.0", path = "../fuels-contract" }
fuels-core = { version = "0.10.0", path = "../fuels-core" }
fuels-signers = { version = "0.10.0", path = "../fuels-signers" }
fuels-test-helpers = { version = "0.10.0", path = "../fuels-test-helpers" }
