[package]
name = "fuels-signers"
version = "0.31.1"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK signers."

[dependencies]
async-trait = { version = "0.1.50", default-features = false }
bytes = { version = "1.1.0", features = ["serde"] }
chrono = "0.4.2"
elliptic-curve = { version = "0.11.6", default-features = false }
eth-keystore = { version = "0.3.0" }
fuel-core = { version = "0.14", default-features = false, optional = true }
fuel-crypto = { version = "0.6", features = ["random"] }
fuel-gql-client = { version = "0.14", default-features = false }
fuel-types = { version = "0.5", default-features = false, features = ["random"] }
fuels-core = { version = "0.31.1", path = "../fuels-core" }
fuels-types = { version = "0.31.1", path = "../fuels-types" }
hex = { version = "0.4.3", default-features = false, features = ["std"] }
rand = { version = "0.8.4", default-features = false }
serde = { version = "1.0.124", default-features = true, features = ["derive"] }
sha2 = { version = "0.9.8", default-features = false }
thiserror = { version = "1.0.30", default-features = false }
tokio = { version = "1.10.1", features = ["full"] }

[dev-dependencies]
fuels = { path = "../fuels" }
fuels-test-helpers = { path = "../fuels-test-helpers", default-features = false }
hex = { version = "0.4.3", default-features = false, features = ["std"] }
tempfile = "3.3.0"

[features]
test-helpers = ["fuel-core"]
