# Generated by Cargo
# will have compiled files and executables
target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk

# Don't add the generated MDBook artifacts
docs/book/

# Don't add Forc lock files
**/Forc.lock

# Don't add out/ files from test Sway projects.
e2e/sway/**/out/
e2e/sway/**/.gitignore

.env

output_changelog.md
