[package]
name = "fuels-example-contracts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuels = { version = "0.14.1", path = "../../packages/fuels" }
fuels-abigen-macro = { version = "0.14.1", path = "../../packages/fuels-abigen-macro" }
rand = "0.8"
tokio = { version = "1.10", features = ["full"] }
