[package]
name = "fuels-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuel-types = { git = "ssh://git@github.com/FuelLabs/fuel-types.git", default-features = false }
sha2 = { version = "0.9.5", optional = true }
strum = "0.21"
strum_macros = "0.21"

[dev-dependencies]
hex = { version = "0.4.3", default-features = false, features = ["std"] }

[features]
default = ["fuel-types/default", "sha2"]
no-std = ["fuel-types/serde-types-minimal"]
