[package]
name = "fuels-test-helpers"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Rust SDK test helpers."

[dependencies]
fuel-core = { workspace = true, default-features = false, optional = true }
fuel-core-chain-config = { workspace = true }
fuel-core-client = { workspace = true }
fuel-core-poa = { workspace = true }
fuel-core-services = { workspace = true }
fuel-tx = { workspace = true }
fuel-types = { workspace = true, features = ["random"] }
fuels-accounts = { workspace = true, optional = true }
fuels-core = { workspace = true }
futures = { workspace = true }
hex = { workspace = true, default-features = false, features = ["std", "serde"] }
portpicker = { workspace = true }
rand = { workspace = true, default-features = false }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
serde_with = { workspace = true }
tempfile = { workspace = true, default-features = false }
tokio = { workspace = true, default-features = false }
which = { workspace = true, default-features = false }

[features]
default = ["fuels-accounts", "std"]
std = ["fuels-accounts?/std", "fuels-core/std"]
fuel-core-lib = ["fuel-core"]
