[package]
name = "fuels-test-helpers"
version = "0.14.1"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK test helpers."

[dependencies]
fuel-core = { version = "0.8", default-features = false }
fuel-gql-client = { version = "0.8", default-features = false }
fuels-core = { version = "0.14.1", path = "../fuels-core" }
fuels-signers = { version = "0.14.1", path = "../fuels-signers", optional = true }
rand = { version = "0.8.4", default-features = false }
tokio = "1.15"

[features]
default = ["fuels-signers"]
