[package]
name = "fuels-test-helpers"
version = "0.16.1"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK test helpers."

[dependencies]
fuel-core = { version = "0.9", default-features = false, optional = true }
fuel-core-interfaces = { version = "0.9", default-features = false }
fuel-gql-client = { version = "0.9", default-features = false }
fuel-types = { version = "0.5", default-features = false, features = ["random"] }
fuels-contract = { version = "0.16.1", path = "../fuels-contract" }
fuels-core = { version = "0.16.1", path = "../fuels-core" }
fuels-signers = { version = "0.16.1", path = "../fuels-signers", optional = true }

hex = { version = "0.4.3", default-features = false, features = ["std", "serde"] }
portpicker = { version = "0.1.1" }
rand = { version = "0.8.4", default-features = false }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
serde_with = { version = "1.11", features = ["serde_json"] }
tempfile = { version = "3.0.1", default-features = false }
tokio = { version = "1.15", default-features = false }

[features]
default = ["fuels-signers"]
fuel-core-lib = ["fuel-core"]
