[package]
name = "fuels-test-helpers"
version = "0.10.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK test helpers."

[dependencies]
fuel-core = { version = "0.6", default-features = false }
fuel-crypto = "0.4"
fuel-gql-client = { version = "0.6", default-features = false }
fuel-types = { version = "0.3", default-features = false }
fuels-signers = { version = "0.10.0", path = "../fuels-signers", optional = true }
fuel-tx = "0.9"
rand = { version = "0.8.4", default-features = false }
secp256k1 = { version = "0.20", features = ["recovery"] }

[features]
default = ["fuels-signers"]
