[package]
name = "fuels-test-helpers"
version = "0.34.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK test helpers."

[dependencies]
fuel-vm = { workspace = true }
fuel-tx = { workspace = true }
fuel-core = { workspace = true, default-features = false, optional = true }
fuel-core-chain-config = { workspace = true, default-features = false }
fuel-core-types = { workspace = true, default-features = false }
fuel-core-client = { workspace = true, default-features = false }
fuel-types = { workspace = true, default-features = false, features = ["random"] }
fuels-programs = { version = "0.34.0", path = "../fuels-programs" }
fuels-core = { version = "0.34.0", path = "../fuels-core" }
fuels-signers = { version = "0.34.0", path = "../fuels-signers", optional = true }
fuels-types = { version = "0.34.0", path = "../fuels-types" }
hex = { version = "0.4.3", default-features = false, features = ["std", "serde"] }
portpicker = { version = "0.1.1" }
rand = { version = "0.8.4", default-features = false }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
serde_with = { version = "1.11", features = ["serde_json"] }
tempfile = { version = "3.0.1", default-features = false }
tokio = { version = "1.15", default-features = false }
which = { version = "4.3", default-features = false }

[features]
default = ["fuels-signers"]
fuel-core-lib = ["fuel-core"]
