[package]
name = "fuels-test-helpers"
version = "0.13.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK test helpers."

[dependencies]
fuel-core = { version = "0.7", default-features = false }
fuel-crypto = "0.5"
fuel-gql-client = { version = "0.7", default-features = false }
fuel-types = { version = "0.5", default-features = false }
fuels-signers = { version = "0.13.0", path = "../fuels-signers", optional = true }
fuel-tx = "0.10"
rand = { version = "0.8.4", default-features = false }
tokio = "1.15"

[features]
default = ["fuels-signers"]
