[package]
name = "fuels-test-helpers"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Fuel Rust SDK test helpers."

[dependencies]
fuel-core = { workspace = true, features = ["test-helpers"], optional = true }
fuel-core-chain-config = { workspace = true, features = [
  "test-helpers",
  "std",
] }
fuel-core-client = { workspace = true }
fuel-core-poa = { workspace = true }
fuel-core-services = { workspace = true }
fuel-crypto = { workspace = true }
fuel-tx = { workspace = true }
fuel-types = { workspace = true, features = ["random"] }
fuels-accounts = { workspace = true, features = ["std"] }
fuels-core = { workspace = true, features = ["std"] }
futures = { workspace = true }
portpicker = { workspace = true }
rand = { workspace = true, default-features = false }
tempfile = { workspace = true, default-features = false }
tokio = { workspace = true, default-features = false }
which = { workspace = true, default-features = false }

[features]
default = ["std"]
std = ["fuels-accounts/std", "fuels-core/std", "fuel-core-chain-config/std"]
fuel-core-lib = ["dep:fuel-core"]
