[package]
name = "fuels-metamask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.18.0"
ethers-providers = "0.17.0"
ethers-signers = "0.17.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = true }
tokio = "1.15.0"
ethers-core = "0.17.0"
webbrowser = "0.8.0"
jsonrpc = "0.13.0"
ethereum-types = "0.14.0"
hex = "0.4.3"
js-sandbox = "0.1.6"
ethers = "0.17.0"
axum = { version = "0.6.0-rc.2" }
