[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "lib_contract"

[dependencies]
lib_contract_abi = { path = "../lib_contract_abi/", package = "lib_contract_abi" }
