[package]
name = "fuels-abi-cli"
version = "0.20.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK CLI tool to parse ABI."

[dependencies]
anyhow = "1"
fuels-contract = { version = "0.20.0", path = "../../crates/fuels-contract" }
fuels-core = { version = "0.20.0", path = "../../crates/fuels-core" }
fuels-types = { version = "0.20.0", path = "../../crates/fuels-types" }
hex = "0.4"
itertools = "0.10"
structopt = "0.3"
