[package]
name = "fuels-test-helpers-bin"
version = "0.0.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK test helpers using fuel-core.bin."
publish = false

[dependencies]
fuel-core-interfaces = { version = "0.8", default-features = false}
fuel-gql-client = { version = "0.8", default-features = false }
fuel-types = { version = "0.5", default-features = false, features = ["random"]}
fuels-core = { path = "../fuels-core" }
fuels-signers = { path = "../fuels-signers"}
hex = { version = "0.4", features = ["serde"]}
portpicker = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"]}
serde_with = "1.11"
tempfile = "3.0.1"
tokio = "1.15"



