[package]
name = "fuels-test-helpers-bin"
version = "0.1.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK test helpers using fuel-core.bin."


[dependencies]
fuel-gql-client = { version = "0.8", default-features = false }
fuels-core = { version = "0.14.1", path = "../fuels-core" }
fuel-core-interfaces = { version = "0.8", default-features = false}
fuels-signers = { version = "0.14.1", path = "../fuels-signers"}
fuel-types = { version = "0.5", default-features = false, features = ["random"]}
hex = { version = "0.4", features = ["serde"]}
portpicker = "0.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"]}
serde_with = {version = "1.11"}
tempfile = "3.0.1"
tokio = {version = "1.15"}



