[project]
name = "something"
version = "0.1.0"
authors = ["Ahmed Sagdati"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
fuels = { path = FUELS_PACKAGE_PATH }
tokio = { version = "1.12", features = ["rt", "macros"] }
