[package]
name = "fuels-types"
version = "0.34.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Serializable type representation for working with the Fuel VM ABI."

[dependencies]
regex = "1.6.0"
lazy_static = "1.4.0"
bech32 = "0.9.0"
chrono = "0.4.2"
fuel-tx = "0.23"
fuel-types = "0.5"
fuel-abi-types = "0.2.0"
fuel-core = { version = "0.15", default-features = false, optional = true }
fuel-chain-config = { version = "0.15", default-features = false }
fuel-gql-client = { version = "0.15", default-features = false }
hex = { version = "0.4.3", features = ["std"] }
proc-macro2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.64", default-features = true }
strum = "0.21"
strum_macros = "0.21"
itertools = "0.10.5"
thiserror = { version = "1.0.26", default-features = false }
tokio = "1.15"
fuels-macros = { version = "0.34.0", path = "../fuels-macros" }
