[package]
name = "fuels-types"
version = "0.15.3"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Serializable type representation for working with the Fuel VM ABI."

[dependencies]
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
strum = "0.21"
strum_macros = "0.21"
