[package]
name = "fuels-types"
version = "0.17.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Serializable type representation for working with the Fuel VM ABI."

[dependencies]
anyhow = "1"
fuel-tx = "0.13"
serde_json = { version = "1.0.64", default-features = true }
hex = { version = "0.4.3", features = ["std"] }
proc-macro2 = "1.0"
thiserror = { version = "1.0.26", default-features = false }
serde = { version = "1.0", features = ["derive"] }
strum = "0.21"
strum_macros = "0.21"
