[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "contract_test"

[dependencies]
increment_abi = { path = "../library_test", package = "library_test" }
