[package]
name = "fuels-abigen-macro"
version = "0.34.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK marcros to generate types from ABI."

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11"
fuels-core = { version = "0.34.0", path = "../fuels-core" }
proc-macro2 = "1.0"
quote = "1.0"
rand = "0.8"
syn = "1.0.12"
itertools = "0.10.5"

[dev-dependencies]
trybuild = "1.0.73"

