[package]
name = "fuels-abigen-macro"
version = "0.20.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK marcros to generate types from ABI."

[lib]
proc-macro = true

[dependencies]
fuels-core = { version = "0.20.0", path = "../fuels-core" }
proc-macro2 = "1.0"
quote = "1.0"
rand = "0.8"
syn = "1.0.12"

