[package]
name = "fuels-abigen-macro"
version = "0.10.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuels-rs"
description = "Fuel Rust SDK marcros to generate types from ABI."

[lib]
proc-macro = true

[dependencies]
fuel-tx = "0.9"
fuels-core = { version = "0.10.0", path = "../fuels-core" }
proc-macro2 = "1.0"
quote = "1.0"
rand = "0.8"
syn = "1.0.12"

[dev-dependencies]
fuel-core = { version = "0.6", default-features = false }
fuel-gql-client = { version = "0.6", default-features = false }
fuels = { version = "0.10.0", path = "../fuels" }
hex = { version = "0.4.3", default-features = false, features = ["std"] }
sha2 = "0.9.5"
tokio = "1.15.0"
