name: Docs

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

jobs:
  test:
    uses: FuelLabs/github-actions/.github/workflows/mdbook-docs.yml@mdbook-docs-pre-command
    with:
      docs-src-path: "docs/src"
