name: Docs

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

jobs:
  test:
    uses: FuelLabs/github-actions/.github/workflows/mdbook-docs.yml@master
    with:
      docs-src-path: "docs/src"
      pre-command: 'cargo run --package versions-replacer -- ./docs --manifest-path ./Cargo.toml --filename-regex "\.md$"'
      spellcheck-config-path: 'docs/.spellcheck.yml'
